### ISSUE TITLE
Are you planning support for organizations?

### ISSUE THREAD

**Issue by ghost** [waseem18/Openflock#1]
Are you planning support for organizations?

I tried promoting: https://github.com/fisherman/fisherman

Thanks.

**Comment by waseem18** [comment]
Currently `Organizations` are not supported on Openflock. But we are willing to. Actually Openflock would have something called `Flocks` which would be useful for GitHub organizations. 

But currently you can promote only your personal repositories. Sooner we will support organizations too. :+1:

**Comment by ghost** [comment]
Thanks! Looking forward to that! :+1:
